"""Constraint for editiing locks

Revision ID: 084d0c67190a
Revises: 1ed674b90a85
Create Date: 2025-08-13 22:28:22.761488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '084d0c67190a'
down_revision: Union[str, None] = '1ed674b90a85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('anmial_section_unique', 'crm_editing_locks', ['animal_id', 'section_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('anmial_section_unique', 'crm_editing_locks', type_='unique')
    # ### end Alembic commands ###
