"""Title field added to Role and Permission models for ua localization

Revision ID: 1420108466c8
Revises: c8d5da9b3031
Create Date: 2024-10-09 01:23:00.937197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1420108466c8'
down_revision: Union[str, None] = 'c8d5da9b3031'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('title', sa.String(length=100), nullable=True))
    op.add_column('roles', sa.Column('title', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'title')
    op.drop_column('permissions', 'title')
    # ### end Alembic commands ###
