"""Animal models created

Revision ID: 1eb851aff8d0
Revises: b42be1d3cdba
Create Date: 2025-02-02 17:33:02.913396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1eb851aff8d0'
down_revision: Union[str, None] = 'b42be1d3cdba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crm_animal_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_animal_types_name'), 'crm_animal_types', ['name'], unique=True)
    op.create_table('crm_locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crm_animals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('origin__arrival_date', sa.Date(), nullable=False),
    sa.Column('origin__city', sa.String(length=100), nullable=False),
    sa.Column('origin__address', sa.String(length=100), nullable=True),
    sa.Column('general__animal_type_id', sa.UUID(), nullable=True),
    sa.Column('general__gender', sa.Enum('male', 'female', name='gender'), nullable=False),
    sa.Column('general__weight', sa.Float(), nullable=True),
    sa.Column('general__age', sa.Float(), nullable=True),
    sa.Column('general__specials', sa.String(length=200), nullable=True),
    sa.Column('owner__info', sa.String(length=500), nullable=True),
    sa.Column('comment__text', sa.String(length=1000), nullable=True),
    sa.Column('adoption__country', sa.String(length=50), nullable=True),
    sa.Column('adoption__city', sa.String(length=50), nullable=True),
    sa.Column('adoption__date', sa.Date(), nullable=True),
    sa.Column('adoption__comment', sa.String(length=500), nullable=True),
    sa.Column('death__dead', sa.Boolean(), nullable=False),
    sa.Column('death__date', sa.Date(), nullable=True),
    sa.Column('death__comment', sa.String(length=500), nullable=True),
    sa.Column('sterilization__done', sa.Boolean(), nullable=False),
    sa.Column('sterilization__date', sa.Date(), nullable=True),
    sa.Column('sterilization__comment', sa.String(length=500), nullable=True),
    sa.Column('microchipping__done', sa.Boolean(), nullable=False),
    sa.Column('microchipping__date', sa.Date(), nullable=True),
    sa.Column('microchipping__comment', sa.String(length=500), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['general__animal_type_id'], ['crm_animal_types.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_animals_created_at'), 'crm_animals', ['created_at'], unique=False)
    op.create_index(op.f('ix_crm_animals_death__date'), 'crm_animals', ['death__date'], unique=False)
    op.create_index(op.f('ix_crm_animals_death__dead'), 'crm_animals', ['death__dead'], unique=False)
    op.create_index(op.f('ix_crm_animals_microchipping__date'), 'crm_animals', ['microchipping__date'], unique=False)
    op.create_index(op.f('ix_crm_animals_microchipping__done'), 'crm_animals', ['microchipping__done'], unique=False)
    op.create_index(op.f('ix_crm_animals_name'), 'crm_animals', ['name'], unique=False)
    op.create_index(op.f('ix_crm_animals_origin__arrival_date'), 'crm_animals', ['origin__arrival_date'], unique=False)
    op.create_index(op.f('ix_crm_animals_origin__city'), 'crm_animals', ['origin__city'], unique=False)
    op.create_index(op.f('ix_crm_animals_sterilization__date'), 'crm_animals', ['sterilization__date'], unique=False)
    op.create_index(op.f('ix_crm_animals_sterilization__done'), 'crm_animals', ['sterilization__done'], unique=False)
    op.create_index(op.f('ix_crm_animals_updated_at'), 'crm_animals', ['updated_at'], unique=False)
    op.create_table('crm_animal_locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('date_from', sa.Date(), nullable=False),
    sa.Column('date_to', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['crm_animals.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['crm_locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crm_animal_media',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['crm_animals.id'], ),
    sa.ForeignKeyConstraint(['media_id'], ['media_assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crm_diagnoses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['crm_animals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crm_procedures',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['crm_animals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crm_vaccinations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('is_vaccinated', sa.Boolean(), nullable=False),
    sa.Column('vaccine_type', sa.String(length=100), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['crm_animals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_vaccinations_date'), 'crm_vaccinations', ['date'], unique=False)
    op.create_index(op.f('ix_crm_vaccinations_is_vaccinated'), 'crm_vaccinations', ['is_vaccinated'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crm_vaccinations_is_vaccinated'), table_name='crm_vaccinations')
    op.drop_index(op.f('ix_crm_vaccinations_date'), table_name='crm_vaccinations')
    op.drop_table('crm_vaccinations')
    op.drop_table('crm_procedures')
    op.drop_table('crm_diagnoses')
    op.drop_table('crm_animal_media')
    op.drop_table('crm_animal_locations')
    op.drop_index(op.f('ix_crm_animals_updated_at'), table_name='crm_animals')
    op.drop_index(op.f('ix_crm_animals_sterilization__done'), table_name='crm_animals')
    op.drop_index(op.f('ix_crm_animals_sterilization__date'), table_name='crm_animals')
    op.drop_index(op.f('ix_crm_animals_origin__city'), table_name='crm_animals')
    op.drop_index(op.f('ix_crm_animals_origin__arrival_date'), table_name='crm_animals')
    op.drop_index(op.f('ix_crm_animals_name'), table_name='crm_animals')
    op.drop_index(op.f('ix_crm_animals_microchipping__done'), table_name='crm_animals')
    op.drop_index(op.f('ix_crm_animals_microchipping__date'), table_name='crm_animals')
    op.drop_index(op.f('ix_crm_animals_death__dead'), table_name='crm_animals')
    op.drop_index(op.f('ix_crm_animals_death__date'), table_name='crm_animals')
    op.drop_index(op.f('ix_crm_animals_created_at'), table_name='crm_animals')
    op.drop_table('crm_animals')
    op.drop_table('crm_locations')
    op.drop_index(op.f('ix_crm_animal_types_name'), table_name='crm_animal_types')
    op.drop_table('crm_animal_types')
    # ### end Alembic commands ###
