"""Init data hash storage

Revision ID: 1ed674b90a85
Revises: a403bb637750
Create Date: 2025-08-13 21:21:38.765274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ed674b90a85'
down_revision: Union[str, None] = 'a403bb637750'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('init_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data_hash', sa.String(length=65), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('init_data')
    # ### end Alembic commands ###
