"""CRM location names made unique

Revision ID: 28dca6fafab6
Revises: 1eb851aff8d0
Create Date: 2025-02-03 01:50:58.918577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28dca6fafab6'
down_revision: Union[str, None] = '1eb851aff8d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'crm_locations', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'crm_locations', type_='unique')
    # ### end Alembic commands ###
