"""Add indexes to foreign keys

Revision ID: a403bb637750
Revises: 8ea9f08d9419
Create Date: 2025-08-13 11:09:47.450799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a403bb637750'
down_revision: Union[str, None] = '8ea9f08d9419'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_crm_animal_locations_animal_id'), 'crm_animal_locations', ['animal_id'], unique=False)
    op.create_index(op.f('ix_crm_animal_locations_location_id'), 'crm_animal_locations', ['location_id'], unique=False)
    op.create_index(op.f('ix_crm_animal_media_animal_id'), 'crm_animal_media', ['animal_id'], unique=False)
    op.create_index(op.f('ix_crm_animal_media_media_id'), 'crm_animal_media', ['media_id'], unique=False)
    op.create_index(op.f('ix_crm_animals_created_by_id'), 'crm_animals', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_crm_animals_general__animal_type_id'), 'crm_animals', ['general__animal_type_id'], unique=False)
    op.create_index(op.f('ix_crm_animals_updated_by_id'), 'crm_animals', ['updated_by_id'], unique=False)
    op.create_index(op.f('ix_crm_diagnoses_animal_id'), 'crm_diagnoses', ['animal_id'], unique=False)
    op.create_index(op.f('ix_crm_editing_locks_animal_id'), 'crm_editing_locks', ['animal_id'], unique=False)
    op.create_index(op.f('ix_crm_editing_locks_user_id'), 'crm_editing_locks', ['user_id'], unique=False)
    op.create_index(op.f('ix_crm_procedures_animal_id'), 'crm_procedures', ['animal_id'], unique=False)
    op.create_index(op.f('ix_crm_vaccinations_animal_id'), 'crm_vaccinations', ['animal_id'], unique=False)
    op.create_index(op.f('ix_roles_permissions_permission_id'), 'roles_permissions', ['permission_id'], unique=False)
    op.create_index(op.f('ix_roles_permissions_role_id'), 'roles_permissions', ['role_id'], unique=False)
    op.create_index(op.f('ix_security_tokens_user_id'), 'security_tokens', ['user_id'], unique=False)
    op.create_index(op.f('ix_users_photo_id'), 'users', ['photo_id'], unique=False)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_index(op.f('ix_users_photo_id'), table_name='users')
    op.drop_index(op.f('ix_security_tokens_user_id'), table_name='security_tokens')
    op.drop_index(op.f('ix_roles_permissions_role_id'), table_name='roles_permissions')
    op.drop_index(op.f('ix_roles_permissions_permission_id'), table_name='roles_permissions')
    op.drop_index(op.f('ix_crm_vaccinations_animal_id'), table_name='crm_vaccinations')
    op.drop_index(op.f('ix_crm_procedures_animal_id'), table_name='crm_procedures')
    op.drop_index(op.f('ix_crm_editing_locks_user_id'), table_name='crm_editing_locks')
    op.drop_index(op.f('ix_crm_editing_locks_animal_id'), table_name='crm_editing_locks')
    op.drop_index(op.f('ix_crm_diagnoses_animal_id'), table_name='crm_diagnoses')
    op.drop_index(op.f('ix_crm_animals_updated_by_id'), table_name='crm_animals')
    op.drop_index(op.f('ix_crm_animals_general__animal_type_id'), table_name='crm_animals')
    op.drop_index(op.f('ix_crm_animals_created_by_id'), table_name='crm_animals')
    op.drop_index(op.f('ix_crm_animal_media_media_id'), table_name='crm_animal_media')
    op.drop_index(op.f('ix_crm_animal_media_animal_id'), table_name='crm_animal_media')
    op.drop_index(op.f('ix_crm_animal_locations_location_id'), table_name='crm_animal_locations')
    op.drop_index(op.f('ix_crm_animal_locations_animal_id'), table_name='crm_animal_locations')
    # ### end Alembic commands ###
