"""Added Blob and MediaAsset models

Revision ID: b259760c5c8e
Revises: ca19d3f7428c
Create Date: 2024-06-28 16:19:09.710976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b259760c5c8e'
down_revision: Union[str, None] = 'ca19d3f7428c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('blob_id', sa.UUID(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blobs_blob_id'), 'blobs', ['blob_id'], unique=False)
    op.create_index(op.f('ix_blobs_index'), 'blobs', ['index'], unique=False)
    op.create_table('media_assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('blob_id', sa.UUID(), nullable=False),
    sa.Column('extension', sa.String(length=10), nullable=False),
    sa.Column('content_type', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_assets_created_at'), 'media_assets', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_media_assets_created_at'), table_name='media_assets')
    op.drop_table('media_assets')
    op.drop_index(op.f('ix_blobs_index'), table_name='blobs')
    op.drop_index(op.f('ix_blobs_blob_id'), table_name='blobs')
    op.drop_table('blobs')
    # ### end Alembic commands ###
