"""Title field added to Role and Permission models for ua localization

Revision ID: b42be1d3cdba
Revises: eab61bf2f5b6
Create Date: 2024-11-06 00:06:05.130401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b42be1d3cdba'
down_revision: Union[str, None] = 'eab61bf2f5b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('title', sa.String(length=100), nullable=True))
    op.add_column('roles', sa.Column('title', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'title')
    op.drop_column('permissions', 'title')
    # ### end Alembic commands ###
