"""Set NULL on delete for created_by_id and updated_by_id in crm_animals

Revision ID: b50b48197860
Revises: 192e48154f51
Create Date: 2025-02-18 23:04:01.750165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b50b48197860'
down_revision: Union[str, None] = '192e48154f51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('crm_animals', 'updated_by_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('crm_animals', 'created_by_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('crm_animals_updated_by_id_fkey', 'crm_animals', type_='foreignkey')
    op.drop_constraint('crm_animals_created_by_id_fkey', 'crm_animals', type_='foreignkey')
    op.create_foreign_key(None, 'crm_animals', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'crm_animals', 'users', ['updated_by_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'crm_animals', type_='foreignkey')
    op.drop_constraint(None, 'crm_animals', type_='foreignkey')
    op.create_foreign_key('crm_animals_created_by_id_fkey', 'crm_animals', 'users', ['created_by_id'], ['id'])
    op.create_foreign_key('crm_animals_updated_by_id_fkey', 'crm_animals', 'users', ['updated_by_id'], ['id'])
    op.alter_column('crm_animals', 'created_by_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('crm_animals', 'updated_by_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
