"""User model updated

Revision ID: b50b11a78a92
Revises: c8d5da9b3031
Create Date: 2024-09-28 18:17:11.904530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b50b11a78a92'
down_revision: Union[str, None] = 'c8d5da9b3031'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(length=30), nullable=True))
    op.add_column('users', sa.Column('photo_id', sa.UUID(), nullable=True))
    op.drop_index('ix_users_username', table_name='users')
    op.drop_constraint('username_domain_unique', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(None, 'users', ['phone'])
    op.create_foreign_key(None, 'users', 'media_assets', ['photo_id'], ['id'], ondelete='SET NULL')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('username_domain_unique', 'users', ['username', 'domain'])
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.drop_column('users', 'photo_id')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
