"""Permission model changed

Revision ID: b7421e52f40b
Revises: e921fab861be
Create Date: 2024-07-25 01:27:35.968880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7421e52f40b'
down_revision: Union[str, None] = 'e921fab861be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('entity', sa.String(length=50), nullable=False))
    op.add_column('permissions', sa.Column('operation', sa.String(length=50), nullable=False))
    op.drop_index('ix_permissions_access_right', table_name='permissions')
    op.create_unique_constraint('entity_operation_unique', 'permissions', ['entity', 'operation'])
    op.create_index(op.f('ix_permissions_entity'), 'permissions', ['entity'], unique=False)
    op.create_index(op.f('ix_permissions_operation'), 'permissions', ['operation'], unique=False)
    op.drop_column('permissions', 'access_right')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('access_right', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_permissions_operation'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_entity'), table_name='permissions')
    op.drop_constraint('entity_operation_unique', 'permissions', type_='unique')
    op.create_index('ix_permissions_access_right', 'permissions', ['access_right'], unique=True)
    op.drop_column('permissions', 'operation')
    op.drop_column('permissions', 'entity')
    # ### end Alembic commands ###
