"""Init

Revision ID: ca19d3f7428c
Revises:
Create Date: 2024-06-27 21:49:03.887499

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ca19d3f7428c"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """..."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """..."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
