"""Added permission model

Revision ID: e921fab861be
Revises: b259760c5c8e
Create Date: 2024-07-24 00:23:23.195745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e921fab861be'
down_revision: Union[str, None] = 'b259760c5c8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('access_right', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_access_right'), 'permissions', ['access_right'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_permissions_access_right'), table_name='permissions')
    op.drop_table('permissions')
    # ### end Alembic commands ###
