name: Ping FastAPI App

on:
  push:
    branches:
      - release/dev
  schedule:
    - cron: "0/5 7-20 * * *"

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Ping FastAPI app
        run: |
          curl -X GET https://animalrescuekharkiv-backend.onrender.com/healthcheck
