name: Start Render Web Services

on:
  push:
    branches:
      - release/dev
      - release/uat
  schedule:
    - cron: "0 5 * * *" # Every day at 5:00 AM UTC (which corresponds to 8:00 AM Kyiv time)

jobs:
  start_service:
    runs-on: ubuntu-latest
    steps:
      - name: Start DEV Service
        run: |
          curl -X POST "https://api.render.com/v1/services/cupbchpopnds7392j3mg/start" \
          -H "Authorization: Bearer rnd_8rqkfGCoMqcsZBEFSCIO1zVGIGR6"
      - name: Start UAT Service
        run: |
          curl -X POST "https://api.render.com/v1/services/cupdlvpopnds73938vjg/start" \
          -H "Authorization: Bearer rnd_URkLeA0rZaaK3hASQpb6Sf7n51dC"
