name: Start Render Web Services

on:
  push:
    branches:
      - release/dev
      - release/uat
  schedule:
    - cron: "0 5 * * *" # Every day at 5:00 AM UTC (which corresponds to 8:00 AM Kyiv time)

jobs:
  start_service:
    runs-on: ubuntu-latest
    steps:
      - name: Start DEV Service
        run: |
          curl -X GET "https://api.render.com/deploy/srv-cupbchpopnds7392j3mg?key=0HdB10irUeI"
      - name: Start UAT Service
        run: |
          curl -X GET "https://api.render.com/deploy/srv-cupdlvpopnds73938vjg?key=TY5yh7vuSOc"
